### ISSUE TITLE
eval.cpp:1818: phase != Phase::Template: Failed to evaluate template constant {kind: ImplWitnessAccess ...

### ISSUE THREAD

**Issue by danakj** [carbon-language/carbon-lang#4868]
### Description of the bug:

I derived this from the [explorer fuzzer corpus ca69be54b8273f334ab8c7db0ad454c5ff0291c9](https://github.com/carbon-language/carbon-lang/blob/7d2958ad37571d2a76deb5554daa8672cea518de/toolchain/check/fuzzer_corpus/ca69be54b8273f334ab8c7db0ad454c5ff0291c9). I introduced a check failure in #4865 once the toolchain began successfully deducing a facet value generic parameter. But when I remove the deduced parameters from the function and make them explicit, I see the same check happening on trunk.

```
// Part of the Carbon Language project, under the Apache License v2.0 with LLVM
// Exceptions. See /LICENSE for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// AUTOUPDATE
// TIP: To test this file alone, run:
// TIP:   bazel test //toolchain/testing:file_test --test_arg=--file_tests=toolchain/check/testdata/builtin_conversions/no_prelude/fail_fuzzer.carbon
// TIP: To dump output, run:
// TIP:   bazel run //toolchain/testing:file_test -- --dump_output --file_tests=toolchain/check/testdata/builtin_conversions/no_prelude/fail_fuzzer.carbon

// --- core.carbon

package Core;

interface ImplicitAs(T:! type) {
  fn Convert[self: Self]() -> T;
}

// --- fail_fuzzer.carbon

library "[[@TEST_NAME]]";

import Core;

interface Generic(Scalar:! type) {
  fn F();
}

class GenericParam {}

class ImplsGeneric {}
impl ImplsGeneric as Generic(GenericParam) {
  fn F() {}
}

fn CallGenericMethod(T:! type, U:! Generic(T)) {
  U.F();
}

fn G() {
  CallGenericMethod(GenericParam, ImplsGeneric);
}
```

```
= toolchain/check/testdata/builtin_conversions/no_prelude/fail_fuzzer.carbon
Please report issues to https://github.com/carbon-language/carbon-lang/issues and include the crash backtrace.
Stack dump:
0.      Program arguments: /home/danakj/.cache/bazel/_bazel_danakj/f53348a8d29407484bf50bee0f9ff0bc/execroot/_main/bazel-out/k8-fastbuild/bin/toolchain/testing/file_test.runfiles/_main/toolchain/testing/file_test --test_targets_file=toolchain/testing/file_test.tests --dump_output --file_tests=toolchain/check/testdata/builtin_conversions/no_prelude/fail_fuzzer.carbon
1.      Program arguments: compile --include-diagnostic-kind --phase=check --dump-sem-ir --no-prelude-import --exclude-dump-file-prefix=/home/danakj/.cache/bazel/_bazel_danakj/f53348a8d29407484bf50bee0f9ff0bc/execroot/_main/bazel-out/k8-fastbuild/bin/toolchain/install/prefix_root/lib/carbon/../../lib/carbon/core core.carbon fail_fuzzer.carbon
2.      Pending diagnostics:
fail_fuzzer.carbon:22:3: error: value of type `<type of F>` is not callable [CallToNonCallable]
  U.F();
  ^~~~~
3.      Check::Context
          NodeStack:
          inst_block_stack_:
            0.  inst_block<none>        {inst12, inst13, inst21, inst42, inst47, inst55, inst60, inst84, inst118}
          pattern_block_stack_:
          param_and_arg_refs_stack:
          args_type_info_stack_:
 #0 0x000055d5e4eb23c9 ___interceptor_backtrace (/home/danakj/.cache/bazel/_bazel_danakj/f53348a8d29407484bf50bee0f9ff0bc/execroot/_main/bazel-out/k8-fastbuild/bin/toolchain/testing/file_test.runfiles/_main/toolchain/testing/file_test+0xb97f3c9)
 #1 0x000055d5f1c54296 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/Unix/Signals.inc:800:13
 #2 0x000055d5f1c54d8b PrintStackTraceSignalHandler(void*) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/Unix/Signals.inc:876:1
 #3 0x000055d5f1c4e8e0 llvm::sys::RunSignalHandlers() /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/Signals.cpp:106:18
 #4 0x000055d5f1c550d3 SignalHandler(int) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/Unix/Signals.inc:0:3
 #5 0x00007fab72404590 (/lib/x86_64-linux-gnu/libc.so.6+0x3f590)
 #6 0x00007fab724533ac __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
 #7 0x00007fab724044f2 raise ./signal/../sysdeps/posix/raise.c:27:6
 #8 0x00007fab723ed4ed abort ./stdlib/abort.c:81:7
 #9 0x000055d5f1524d5d Carbon::Internal::CheckFailImpl(char const*, char const*, int, char const*, llvm::StringRef) /proc/self/cwd/common/check_internal.cpp:42:3
#10 0x000055d5e7aeaa64 void Carbon::Internal::CheckFail<Carbon::TemplateString<5>{char [6]{(char)67, (char)72, (char)69, (char)67, (char)75}}, Carbon::TemplateString<24>{char [25]{(char)116, (char)111, (char)111, (char)108, (char)99, (char)104, (char)97, (char)105, (char)110, (char)47, (char)99, (char)104, (char)101, (char)99, (char)107, (char)47, (char)101, (char)118, (char)97, (char)108, (char)46, (char)99, (char)112, (char)112}}, 1818, Carbon::TemplateString<24>{char [25]{(char)112, (char)104, (char)97, (char)115, (char)101, (char)32, (char)33, (char)61, (char)32, (char)80, (char)104, (char)97, (char)115, (char)101, (char)58, (char)58, (char)84, (char)101, (char)109, (char)112, (char)108, (char)97, (char)116, (char)101}}, Carbon::TemplateString<50>{char [51]{(char)70, (char)97, (char)105, (char)108, (char)101, (char)100, (char)32, (char)116, (char)111, (char)32, (char)101, (char)118, (char)97, (char)108, (char)117, (char)97, (char)116, (char)101, (char)32, (char)116, (char)101, (char)109, (char)112, (char)108, (char)97, (char)116, (char)101, (char)32, (char)99, (char)111, (char)110, (char)115, (char)116, (char)97, (char)110, (char)116, (char)32, (char)123, (char)48, (char)125, (char)32, (char)97, (char)114, (char)103, (char)48, (char)58, (char)32, (char)123, (char)49, (char)125}}, Carbon::SemIR::Inst&, Carbon::SemIR::Inst>(Carbon::SemIR::Inst&, Carbon::SemIR::Inst&&) /proc/self/cwd/./common/check_internal.h:0:5
#11 0x000055d5e7adf6dd Carbon::Check::TryEvalInstInContext(Carbon::Check::(anonymous namespace)::EvalContext&, Carbon::SemIR::InstId, Carbon::SemIR::Inst) /proc/self/cwd/toolchain/check/eval.cpp:0:11
#12 0x000055d5e7ae2370 Carbon::Check::TryEvalBlockForSpecific(Carbon::Check::Context&, Carbon::Check::SemIRLoc, Carbon::SemIR::SpecificId, Carbon::SemIR::GenericInstIndex::Region) /proc/self/cwd/toolchain/check/eval.cpp:0:0
#13 0x000055d5e7b14e35 Carbon::Check::ResolveSpecificDefinition(Carbon::Check::Context&, Carbon::Check::SemIRLoc, Carbon::SemIR::SpecificId) /proc/self/cwd/toolchain/check/generic.cpp:0:32
#14 0x000055d5e78591fc Carbon::Check::CheckUnit::CheckRequiredDefinitions() /proc/self/cwd/toolchain/check/check_unit.cpp:449:13
#15 0x000055d5e78559a4 Carbon::Check::CheckUnit::Run() /proc/self/cwd/toolchain/check/check_unit.cpp:76:12
#16 0x000055d5e783357e Carbon::Check::CheckParseTrees(llvm::MutableArrayRef<Carbon::Check::Unit>, bool, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, llvm::raw_ostream*, bool) /proc/self/cwd/toolchain/check/check.cpp:0:57
#17 0x000055d5e51f2c45 release /proc/self/cwd/external/+llvm_project+llvm-project/llvm/include/llvm/ADT/IntrusiveRefCntPtr.h:232:9
#18 0x000055d5e51f2c45 ~IntrusiveRefCntPtr /proc/self/cwd/external/+llvm_project+llvm-project/llvm/include/llvm/ADT/IntrusiveRefCntPtr.h:196:27
#19 0x000055d5e51f2c45 Carbon::CompileSubcommand::Run(Carbon::DriverEnv&) /proc/self/cwd/toolchain/driver/compile_subcommand.cpp:869:3
#20 0x000055d5e51eacfd Carbon::Driver::RunCommand(llvm::ArrayRef<llvm::StringRef>) /proc/self/cwd/toolchain/driver/driver.cpp:0:39
#21 0x000055d5e4f4ced0 Carbon::Testing::(anonymous namespace)::ToolchainFileTest::Run(llvm::SmallVector<llvm::StringRef, 3u> const&, llvm::IntrusiveRefCntPtr<llvm::vfs::InMemoryFileSystem>&, _IO_FILE*, llvm::raw_pwrite_stream&, llvm::raw_pwrite_stream&) /proc/self/cwd/toolchain/testing/file_test.cpp:0:31
#22 0x000055d5e4f77c88 Carbon::Testing::FileTestBase::ProcessTestFileAndRun(Carbon::Testing::FileTestBase::TestContext&) /proc/self/cwd/testing/file_test/file_test_base.cpp:374:3
#23 0x000055d5e4f7e49a index /usr/lib/llvm-17/bin/../include/c++/v1/variant:821:12
#24 0x000055d5e4f7e49a index /usr/lib/llvm-17/bin/../include/c++/v1/variant:1474:60
#25 0x000055d5e4f7e49a __holds_alternative<1UL, Carbon::Error, Carbon::Success> /usr/lib/llvm-17/bin/../include/c++/v1/variant:1500:14
#26 0x000055d5e4f7e49a holds_alternative<Carbon::Success, Carbon::Error, Carbon::Success> /usr/lib/llvm-17/bin/../include/c++/v1/variant:1506:10
#27 0x000055d5e4f7e49a ok /proc/self/cwd/./common/error.h:90:36
#28 0x000055d5e4f7e49a Carbon::Testing::FileTestBase::DumpOutput() /proc/self/cwd/testing/file_test/file_test_base.cpp:268:19
#29 0x000055d5e4f8dc3f Main /proc/self/cwd/testing/file_test/file_test_base.cpp:0:27
#30 0x000055d5e4f8dc3f main /proc/self/cwd/testing/file_test/file_test_base.cpp:1201:10
#31 0x00007fab723eec8a __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:74:3
#32 0x00007fab723eed45 call_init ./csu/../csu/libc-start.c:128:20
#33 0x00007fab723eed45 __libc_start_main ./csu/../csu/libc-start.c:347:5
#34 0x000055d5e4e6bfe1 _start (/home/danakj/.cache/bazel/_bazel_danakj/f53348a8d29407484bf50bee0f9ff0bc/execroot/_main/bazel-out/k8-fastbuild/bin/toolchain/testing/file_test.runfiles/_main/toolchain/testing/file_test+0xb938fe1)
CHECK failure at toolchain/check/eval.cpp:1818: phase != Phase::Template: Failed to evaluate template constant {kind: ImplWitnessAccess, arg0: inst115, arg1: element0, type: type(symbolic_constant40)} arg0: {kind: FacetAccessWitness, arg0: inst48, type: type(inst(WitnessType))}
external/bazel_tools/tools/test/test-setup.sh: line 335: 2249647 Aborted                 (core dumped) "${TEST_PATH}" "$@" 2>&1
```

edit: fixed the stack trace to be complete
