### ISSUE TITLE
`CARBON_CHECK()` causes test timeout in a language server test

### ISSUE THREAD

**Issue by bricknerb** [carbon-language/carbon-lang#5042]
### Description of the bug:

When adding a simple `CARBON_CHECK(ptr != nullptr);` the following test run timeouts:

```
bazel test //toolchain/testing:file_test --test_arg=--file_tests=toolchain/language_server/testdata/document_symbol/nested.carbon
```

Output of the test (after it timed out):

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //toolchain/testing:file_test
-----------------------------------------------------------------------------
Running tests with 128 thread(s)
Please report issues to https://github.com/carbon-language/carbon-lang/issues and include the crash backtrace.
Stack dump:
0.	bazel test //toolchain/testing:file_test --test_arg=--file_tests=toolchain/language_server/testdata/document_symbol/nested.carbon
1.	Program arguments: --include-diagnostic-kind language-server
2.	Check::Context
          NodeStack:
          inst_block_stack_:
            0.	inst_block<none>	{inst12}
          pattern_block_stack_:
          param_and_arg_refs_stack:
          args_type_info_stack_:
 #0 0x000055aa41c4328b backtrace (/usr/local/google/home/brickner/.cache/bazel/_bazel_brickner/ea6b91bc246d550975e63f83247d1a54/sandbox/linux-sandbox/141/execroot/_main/bazel-out/k8-fastbuild/bin/toolchain/testing/file_test.runfiles/_main/toolchain/testing/file_test+0x10cba28b)
 #1 0x000055aa4ea5a4a6 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/Unix/Signals.inc:803:8
 #2 0x000055aa4ea5b04b PrintStackTraceSignalHandler(void*) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/Unix/Signals.inc:875:1
 #3 0x000055aa4ea54b7d llvm::sys::RunSignalHandlers() /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/Signals.cpp:106:18
 #4 0x000055aa4ea58cbc llvm::sys::CleanupOnSignal(unsigned long) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/Unix/Signals.inc:370:1
 #5 0x000055aa4e98c47e (anonymous namespace)::CrashRecoveryContextImpl::HandleCrash(int, unsigned long) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/CrashRecoveryContext.cpp:73:5
 #6 0x000055aa4e98cad1 CrashRecoverySignalHandler(int) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/CrashRecoveryContext.cpp:0:51
 #7 0x00007ff3a3ab6590 (/lib/x86_64-linux-gnu/libc.so.6+0x3f590)
 #8 0x00007ff3a3b053ac __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
 #9 0x00007ff3a3ab64f2 raise ./signal/../sysdeps/posix/raise.c:27:6
#10 0x00007ff3a3a9f4ed abort ./stdlib/abort.c:81:7
#11 0x000055aa4e3000ed Carbon::Internal::CheckFailImpl(char const*, char const*, int, char const*, llvm::StringRef) /proc/self/cwd/common/check_internal.cpp:42:3
#12 0x000055aa4443693d void Carbon::Internal::CheckFail<Carbon::TemplateString<5>{char [6]{(char)67, (char)72, (char)69, (char)67, (char)75}}, Carbon::TemplateString<30>{char [31]{(char)116, (char)111, (char)111, (char)108, (char)99, (char)104, (char)97, (char)105, (char)110, (char)47, (char)99, (char)104, (char)101, (char)99, (char)107, (char)47, (char)99, (char)104, (char)101, (char)99, (char)107, (char)95, (char)117, (char)110, (char)105, (char)116, (char)46, (char)99, (char)112, (char)112}}, 144, Carbon::TemplateString<21>{char [22]{(char)109, (char)121, (char)95, (char)112, (char)111, (char)105, (char)110, (char)116, (char)101, (char)114, (char)32, (char)33, (char)61, (char)32, (char)110, (char)117, (char)108, (char)108, (char)112, (char)116, (char)114}}, Carbon::TemplateString<0>{}>() /proc/self/cwd/./common/check_internal.h:102:1
#13 0x000055aa44432dd2 Carbon::Check::CheckUnit::InitPackageScopeAndImports() /proc/self/cwd/toolchain/check/check_unit.cpp:0:3
#14 0x000055aa44432145 Carbon::Check::CheckUnit::Run() /proc/self/cwd/toolchain/check/check_unit.cpp:0:0
#15 0x000055aa444161dc Carbon::Check::CheckParseTrees(llvm::MutableArrayRef<Carbon::Check::Unit>, bool, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, llvm::raw_ostream*, bool) /proc/self/cwd/toolchain/check/check.cpp:0:70
#16 0x000055aa4440636a release /proc/self/cwd/external/+llvm_project+llvm-project/llvm/include/llvm/ADT/IntrusiveRefCntPtr.h:232:9
#17 0x000055aa4440636a ~IntrusiveRefCntPtr /proc/self/cwd/external/+llvm_project+llvm-project/llvm/include/llvm/ADT/IntrusiveRefCntPtr.h:196:27
#18 0x000055aa4440636a Carbon::LanguageServer::Context::File::SetText(Carbon::LanguageServer::Context&, std::__1::optional<long>, llvm::StringRef) /proc/self/cwd/toolchain/language_server/context.cpp:150:3
#19 0x000055aa443fd327 Carbon::LanguageServer::HandleDidOpenTextDocument(Carbon::LanguageServer::Context&, clang::clangd::DidOpenTextDocumentParams const&) /proc/self/cwd/toolchain/language_server/handle_text_document.cpp:22:7
#20 0x000055aa443f1a27 void Carbon::LanguageServer::IncomingMessages::AddNotificationHandler<clang::clangd::DidOpenTextDocumentParams>(llvm::StringRef, void (*)(Carbon::LanguageServer::Context&, clang::clangd::DidOpenTextDocumentParams const&))::'lambda'(Carbon::LanguageServer::Context&, llvm::json::Value)::operator()(Carbon::LanguageServer::Context&, llvm::json::Value) const /proc/self/cwd/toolchain/language_server/incoming_messages.cpp:0:5
#21 0x000055aa443f1755 ~Value /proc/self/cwd/external/+llvm_project+llvm-project/llvm/include/llvm/Support/JSON.h:382:14
#22 0x000055aa443f1755 __invoke<(lambda at toolchain/language_server/incoming_messages.cpp:56:7) &, Carbon::LanguageServer::Context &, llvm::json::Value> /usr/lib/llvm-16/bin/../include/c++/v1/__functional/invoke.h:394:7
#23 0x000055aa443f1755 __call<(lambda at toolchain/language_server/incoming_messages.cpp:56:7) &, Carbon::LanguageServer::Context &, llvm::json::Value> /usr/lib/llvm-16/bin/../include/c++/v1/__functional/invoke.h:487:9
#24 0x000055aa443f1755 operator() /usr/lib/llvm-16/bin/../include/c++/v1/__functional/function.h:185:16
#25 0x000055aa443f1755 std::__1::__function::__func<void Carbon::LanguageServer::IncomingMessages::AddNotificationHandler<clang::clangd::DidOpenTextDocumentParams>(llvm::StringRef, void (*)(Carbon::LanguageServer::Context&, clang::clangd::DidOpenTextDocumentParams const&))::'lambda'(Carbon::LanguageServer::Context&, llvm::json::Value), std::__1::allocator<void Carbon::LanguageServer::IncomingMessages::AddNotificationHandler<clang::clangd::DidOpenTextDocumentParams>(llvm::StringRef, void (*)(Carbon::LanguageServer::Context&, clang::clangd::DidOpenTextDocumentParams const&))::'lambda'(Carbon::LanguageServer::Context&, llvm::json::Value)>, void (Carbon::LanguageServer::Context&, llvm::json::Value)>::operator()(Carbon::LanguageServer::Context&, llvm::json::Value&&) /usr/lib/llvm-16/bin/../include/c++/v1/__functional/function.h:356:12
#26 0x000055aa443dfcec ~Value /proc/self/cwd/external/+llvm_project+llvm-project/llvm/include/llvm/Support/JSON.h:382:14
#27 0x000055aa443dfcec Carbon::LanguageServer::IncomingMessages::onNotify(llvm::StringRef, llvm::json::Value) /proc/self/cwd/toolchain/language_server/incoming_messages.cpp:105:5
#28 0x000055aa444d474c handleMessage /proc/self/cwd/external/+llvm_project+llvm-project/clang-tools-extra/clangd/JSONTransport.cpp:195:0
#29 0x000055aa444d474c clang::clangd::(anonymous namespace)::JSONTransport::loop(clang::clangd::Transport::MessageHandler&) /proc/self/cwd/external/+llvm_project+llvm-project/clang-tools-extra/clangd/JSONTransport.cpp:119:16
#30 0x000055aa443dadfc getPtr /proc/self/cwd/external/+llvm_project+llvm-project/llvm/include/llvm/Support/Error.h:282:12
#31 0x000055aa443dadfc operator bool /proc/self/cwd/external/+llvm_project+llvm-project/llvm/include/llvm/Support/Error.h:242:16
#32 0x000055aa443dadfc Carbon::LanguageServer::Run(_IO_FILE*, llvm::raw_ostream&, llvm::raw_ostream&, llvm::raw_ostream*, Carbon::DiagnosticConsumer&) /proc/self/cwd/toolchain/language_server/language_server.cpp:64:7
#33 0x000055aa41fe6e92 Carbon::LanguageServerSubcommand::Run(Carbon::DriverEnv&) /proc/self/cwd/toolchain/driver/language_server_subcommand.cpp:30:18
#34 0x000055aa41f9065d index /usr/lib/llvm-16/bin/../include/c++/v1/variant:818:12
#35 0x000055aa41f9065d valueless_by_exception /usr/lib/llvm-16/bin/../include/c++/v1/variant:813:12
#36 0x000055aa41f9065d __destroy /usr/lib/llvm-16/bin/../include/c++/v1/variant:875:1
#37 0x000055aa41f9065d ~__dtor /usr/lib/llvm-16/bin/../include/c++/v1/variant:875:1
#38 0x000055aa41f9065d ~variant /usr/lib/llvm-16/bin/../include/c++/v1/variant:1396:22
#39 0x000055aa41f9065d ~ErrorOr /proc/self/cwd/./common/error.h:79:21
#40 0x000055aa41f9065d Carbon::Driver::RunCommand(llvm::ArrayRef<llvm::StringRef>) /proc/self/cwd/toolchain/driver/driver.cpp:137:1
#41 0x000055aa41cd928c Carbon::Testing::(anonymous namespace)::ToolchainFileTest::Run(llvm::SmallVector<llvm::StringRef, 3u> const&, llvm::IntrusiveRefCntPtr<llvm::vfs::InMemoryFileSystem>&, _IO_FILE*, llvm::raw_pwrite_stream&, llvm::raw_pwrite_stream&) /proc/self/cwd/toolchain/testing/file_test.cpp:0:31
#42 0x000055aa41d2f9b6 Carbon::Testing::ProcessTestFileAndRun(Carbon::Testing::FileTestBase*, std::__1::mutex*, bool, bool) /proc/self/cwd/testing/file_test/run_test.cpp:0:50
#43 0x000055aa41d288b2 operator() /proc/self/cwd/testing/file_test/file_test_base.cpp:0:28
#44 0x000055aa41d288b2 void llvm::function_ref<void ()>::callback_fn<Carbon::Testing::FileTestEventListener::OnTestProgramStart(testing::UnitTest const&)::$_0::operator()() const::'lambda'()>(long) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:46:12
#45 0x000055aa4e98c2c9 operator() /proc/self/cwd/external/+llvm_project+llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:0:12
#46 0x000055aa4e98c2c9 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/CrashRecoveryContext.cpp:426:3
#47 0x000055aa41d2802b operator() /proc/self/cwd/testing/file_test/file_test_base.cpp:374:29
#48 0x000055aa41d2802b __invoke<(lambda at testing/file_test/file_test_base.cpp:360:16) &> /usr/lib/llvm-16/bin/../include/c++/v1/__functional/invoke.h:394:23
#49 0x000055aa41d2802b __call<(lambda at testing/file_test/file_test_base.cpp:360:16) &> /usr/lib/llvm-16/bin/../include/c++/v1/__functional/invoke.h:487:9
#50 0x000055aa41d2802b operator() /usr/lib/llvm-16/bin/../include/c++/v1/__functional/function.h:185:16
#51 0x000055aa41d2802b std::__1::__function::__func<Carbon::Testing::FileTestEventListener::OnTestProgramStart(testing::UnitTest const&)::$_0, std::__1::allocator<Carbon::Testing::FileTestEventListener::OnTestProgramStart(testing::UnitTest const&)::$_0>, void ()>::operator()() /usr/lib/llvm-16/bin/../include/c++/v1/__functional/function.h:356:12
#52 0x000055aa41d27a28 std::__1::__deferred_assoc_state<void, std::__1::__async_func<std::__1::function<void ()>>>::__execute() /usr/lib/llvm-16/bin/../include/c++/v1/future:918:15
#53 0x000055aa41d27d27 std::__1::__function::__func<std::__1::shared_future<void> llvm::ThreadPoolInterface::asyncImpl<void>(std::__1::function<void ()>, llvm::ThreadPoolTaskGroup*)::'lambda'(), std::__1::allocator<std::__1::shared_future<void> llvm::ThreadPoolInterface::asyncImpl<void>(std::__1::function<void ()>, llvm::ThreadPoolTaskGroup*)::'lambda'()>, void ()>::operator()() /usr/lib/llvm-16/bin/../include/c++/v1/__functional/function.h:356:5
#54 0x000055aa4ea935e8 operator() /usr/lib/llvm-16/bin/../include/c++/v1/__functional/function.h:0:16
#55 0x000055aa4ea935e8 operator() /usr/lib/llvm-16/bin/../include/c++/v1/__functional/function.h:1156:12
#56 0x000055aa4ea935e8 llvm::StdThreadPool::processTasks(llvm::ThreadPoolTaskGroup*) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/ThreadPool.cpp:100:5
#57 0x000055aa4ea96360 GenericThreadProxy<std::__1::tuple<(lambda at external/+llvm_project+llvm-project/llvm/lib/Support/ThreadPool.cpp:45:26)> > /proc/self/cwd/external/+llvm_project+llvm-project/llvm/lib/Support/ThreadPool.cpp:0:7
#58 0x000055aa4ea96360 void* llvm::thread::ThreadProxy<std::__1::tuple<llvm::StdThreadPool::grow(int)::$_0>>(void*) /proc/self/cwd/external/+llvm_project+llvm-project/llvm/include/llvm/Support/thread.h:55:5
#59 0x00007ff3a3b036c2 start_thread ./nptl/pthread_create.c:447:8
#60 0x00007ff3a3b7e128 clone3 ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:80:0
CHECK failure at toolchain/check/check_unit.cpp:144: my_pointer != nullptr
-- Test timed out at 2025-02-28 13:57:48 UTC --
```
